name: Build Burp Extension

on:
  workflow_dispatch:  # 添加手动触发选项

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Build with Gradle
      run: |
        chmod +x ./gradlew
        ./gradlew build

    - name: Upload JAR
      uses: actions/upload-artifact@v2
      with:
        name: Burp-Extension
        path: build/libs/*.jar
