name: Build Burp Extension

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number for this release'
        required: true
        default: '1.0.0'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build with Gradle
        run: |
          gradle wrapper
          ./gradlew build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: burp-extension-${{ github.event.inputs.version }}.jar
          path: build/libs/burp-extension-${{ github.event.inputs.version }}.jar
